apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-frontend
  namespace: car-rental
  labels:
    app: car-rental-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-rental-frontend
  template:
    metadata:
      labels:
        app: car-rental-frontend
    spec:
      containers:
        - name: car-rental-frontend
          image: rakizouari/car-rental-frontend:2.0.4
          ports:
            - containerPort: 80
          imagePullPolicy: Always
