apiVersion: v1
kind: ConfigMap
metadata:
  name: car-rental-config
  namespace: car-rental
data:
  EUREKA_HOST: "http://eureka-server:8761"
  MYSQL_HOST: "mysql"
  MYSQL_DATABASE: "carrentaldb"
  MYSQL_USER: "caruser"
